instagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from .views import home, login

urlpatterns = [
    # path("__reload__/", include("django_browser_reload.urls")),
    path('admin/', admin.site.urls),
    path('', home, name="home"),
    path('login/', login, name="login"),
    path('user/', include('users.urls'), name="users"),
    path('posts/', include('posts.urls'), name="posts"),
    path('messenger/', include('messenger.urls'), name="messenger"),
] 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

messenger/urls.py
from django.urls import path
from . import views

app_name = "messenger"
urlpatterns = [
    path('messages', views.messenger, name='home'),
    path('chat/<str:user_id>/', views.chat_user, name='chat'),
    path('sent-message/<int:user_id>', views.sent_message, name="sent-message"),
]

posts/urls.py
from django.urls import path
from . import views

app_name = "posts"
urlpatterns = [
    path('create-post', views.create_post, name='create-post'),
    path('delete-post/<int:post_id>', views.delete_post, name='delete-post'),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    # path('', views.home, name='home'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('register-user/', views.register, name='register-user'),
    path('profile/', views.profile, name='profile'),
    path('profile/<int:user_id>/', views.user_profile, name='user-profile'),
    path('follow/<int:user_id>/', views.follow_user, name='follow'),
    path('unfollow/<int:user_id>/', views.unfollow_user, name='unfollow'),
    path('update-fullname/', views.update_fullname, name='update-fullname'),
    path('update-profilepic/', views.update_profilepic, name='update-profilepic'),
]

messenger/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Message(models.Model):
    from_user = models.ForeignKey(User, related_name="sent_messages", on_delete=models.CASCADE)
    to_user = models.ForeignKey(User, related_name="recieve_messages", on_delete=models.CASCADE)
    message = models.TextField(blank=False, null=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"From: {self.from_user}, To: {self.to_user}"

messenger/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.db.models import Q


from users.models import UserAccount 
from .models import Message 

def messenger(request):
    messages = Message.objects.filter(Q(from_user=request.user.id) | Q(to_user=request.user.id)).order_by('created_at')
    account = UserAccount.objects.get(user_id=request.user.id)
    user = UserAccount.objects.all()
    context = {
        "current_user":account,
        "users": user,
        "all_messages": messages,
        "location":"messenger",
    }
    return render(request, "messenger/messenger.html", context)

def chat_user(request, user_id):
    user = UserAccount.objects.get(user_id=user_id)
    messages = Message.objects.filter(Q(from_user=request.user.id) & Q(to_user=user_id) | Q(from_user=user_id) & Q(to_user=request.user.id)).order_by('created_at')

    context = {
        "chat_user": user,
        "all_messages": messages,
    }
    return render(request, "messenger/chat.html", context)

def sent_message(request, user_id):
    if request.method == 'POST':
        message = request.POST.get('message-input')
        from_user = User.objects.get(id=request.user.id)
        to_user = User.objects.get(id=user_id)
        new_message = Message()
        new_message.from_user = from_user
        new_message.to_user = to_user
        new_message.message = message
        new_message.save()
        previous_url = request.META.get('HTTP_REFERER', None)
        return HttpResponseRedirect(previous_url)

messenger/templates/messenger/chat.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>Messenger</title>    
{% endblock title %}

{% block main_content %}
    <link rel="stylesheet" href="{% static 'messenger/css/chat.css' %}">
    <div class="chat-section">
        {% if chat_user %}
            {% if chat_user.user.useraccount.profile_pic %}
            <img class="h-44 w-44 rounded-full" src="/media/{{chat_user.user.useraccount.profile_pic}}" alt="Profile pic">
        {% else %} 
            <img class="h-44 w-44 rounded-full" src="{% static '/images/user-circle.png' %}" alt="profile pic"> 
        {% endif %} 
            <span class="font-bold text-xl">{{chat_user.user.username}}</span>
            <a href="{% url 'users:user-profile' user_id=chat_user.user_id %}">
                <span class="view-profile">
                    View Profile
                </span>
            </a>
            <div class="messages-section">
                {% if all_messages %}
                    {% for message in all_messages %}
                        <div class="message">
                            {% if message.from_user == user %}
                                <div class="messages-sent">
                                    <div class="message-content-sent">
                                        <h2>You</h2>
                                        <h3>{{message.message}}</h3>
                                        <span style="color:rgb(55, 55, 55);">{{message.created_at}}</span>
                                        <div class="corner"></div>
                                    </div>
                                    {% if message.from_user.useraccount.gender == 'M' %}
                                        <img id="chat-pic" src="{% static 'images/profile2.png' %}" alt="avatar">
                                    {% else %}
                                        <img id="chat-pic" src="{% static 'images/girl.png' %}" alt="avatar">
                                    {% endif %}
                                </div>
                                
                            {% else %}
                                <div class="messages-recieve">
                                    {% if message.from_user.useraccount.gender == 'M' %}
                                        <img id="chat-pic" src="{% static 'images/profile2.png' %}" alt="avatar">
                                    {% else %}
                                        <img id="chat-pic" src="{% static 'images/girl.png' %}" alt="avatar">
                                    {% endif %}
                                    <div class="message-content-recieve">
                                        <h2 style="color:#0067b5;">{{message.from_user}}</h2>
                                        <h3>{{message.message}}</h3>
                                        <span style="color:rgb(55, 55, 55);">{{message.created_at}}</span>
                                        <div class="corner"></div>
                                    </div>
                                </div>
                            {% endif %}
                        </div>
                    {% endfor %}
                {% endif %}
                {% comment %} <form class="sent-message" action="" method="POST">
                    {% csrf_token %} {% endcomment %}
                {% comment %} </form> {% endcomment %}
            </div>
            <div class="message-input-section">
                <input type="text" name="message-input" id="message-input" placeholder="Type here . . ." value="">
                {% comment %} <span class="sent-icon material-symbols-outlined">
                    send
                </span> {% endcomment %}
            </div>
        {% endif %}
            
    </div>
    <script>
        window.scrollTo(0, document.body.scrollHeight);
        window.scrollTo(0, document.documentElement.scrollHeight);
        const messageInput = document.getElementById("message-input");
        const sendMessageButton = document.querySelector(".sent-icon");
        const sendMessage = document.getElementById("send-message");
        messageInput.focus();
        const chatSocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/chat/'
            + '{{user.id}}'
            + '/'
            + '{{chat_user.user_id}}'
            + '/'
        );

        messageInput.addEventListener("keydown", function (event) {
            //messageForm.submit();
            if(event.key == 'Enter'){
                const data = {
                    "message": messageInput.value,
                    "receiver": '{{chat_user.user_id}}',
                    "sender": '{{user.id}}',
                }
                chatSocket.send(JSON.stringify(data));
                messageInput.value = '';
            }
        });

        chatSocket.onmessage = function(e) {
            const data = JSON.parse(e.data);

            const messageContainer = document.createElement('div');
            messageContainer.classList.add('message');

            const messageSent = document.createElement('div');
            if('{{user.id}}' == data.from_user){
                messageSent.classList.add('messages-sent');
            }else{
                messageSent.classList.add('messages-recieve');
            }
              

            const messageContentSent = document.createElement('div');
            if('{{user.id}}' == data.from_user){
                messageContentSent.classList.add('message-content-sent');
            }else{
                messageContentSent.classList.add('message-content-recieve');
            }
            
            const messageContentSentHeading = document.createElement('h2');
            if('{{user.id}}' == data.from_user){
                messageContentSentHeading.textContent = "You";
            }else{
                messageContentSentHeading.textContent = "{{chat_user.user}}";
                messageContentSentHeading.style.color = '#0067b5';
            }
            

            const messageContentSentContent = document.createElement('h3');
            messageContentSentContent.textContent = data.message;

            const messageContentSentContentCorner = document.createElement('div');
            messageContentSentContentCorner.classList.add('corner');

            const messageContentSentImg = document.createElement('img');
            messageContentSentImg.id = "chat-pic";
            if(data.from_user_gender == 'M'){
                messageContentSentImg.src = "{% static '/images/profile2.png' %}";
            }else{
                messageContentSentImg.src = "{% static '/images/girl.png' %}";
            }
            messageContentSentImg.alt = "avatar";

            const messageContentSentContentDate = document.createElement('span');
            const dateString = data.created_at;

            const date = new Date(dateString);
            const months = [
                "Jan.", "Feb.", "Mar.", "Apr.", "May", "Jun.", "Jul.", "Aug.", "Sep.", "Oct.", "Nov.", "Dec."
            ];
            // Get day, month, year
            const day = date.getDate();
            const month = months[date.getMonth()];
            const year = date.getFullYear();
            // Get hours and minutes
            let hours = date.getHours();
            const minutes = date.getMinutes();
            let period = "a.m.";
            // Convert to 12-hour format and determine period (a.m. or p.m.)
            if (hours > 12) {
                hours -= 12;
                period = "p.m.";
            }
            // Construct the formatted date and time string
            const formattedDateString = `${month} ${day}, ${year}, ${hours}:${(minutes < 10 ? '0' : '') + minutes} ${period}`;

            messageContentSentContentDate.textContent = formattedDateString;
            messageContentSentContentDate.style.color = 'rgb(55, 55, 55)';
            
            messageContentSent.appendChild(messageContentSentHeading);
            messageContentSent.appendChild(messageContentSentContent);
            messageContentSent.appendChild(messageContentSentContentDate);
            messageContentSent.appendChild(messageContentSentContentCorner);
            if('{{user.id}}' != data.from_user){
                messageSent.appendChild(messageContentSentImg);
            }
            messageSent.appendChild(messageContentSent);
            if('{{user.id}}' == data.from_user){
                messageSent.appendChild(messageContentSentImg);
            }
            messageContainer.appendChild(messageSent);
            
            // Assuming 'messagesContainer' is a div where you want to append these message containers
            const messagesContainer = document.querySelector('.messages-section');
            messagesContainer.appendChild(messageContainer);

        };

        chatSocket.onclose = function(e) {
            console.error('Chat socket closed unexpectedly');
        };
    </script>
{% endblock main_content %}
    
    

messenger/templates/messenger/messenger.html
{% extends 'base.html' %}
{% block main_content %}
    {% include 'navbar.html' %}
{% endblock main_content %}