instagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from .views import home, login

urlpatterns = [
    # path("__reload__/", include("django_browser_reload.urls")),
    path('admin/', admin.site.urls),
    path('', home, name="home"),
    path('login/', login, name="login"),
    path('user/', include('users.urls'), name="users"),
    path('posts/', include('posts.urls'), name="posts"),
    path('messenger/', include('messenger.urls'), name="messenger"),
] 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

messenger/urls.py
from django.urls import path
from . import views

app_name = "messenger"
urlpatterns = [
    path('messages', views.messenger, name='home'),
    path('chat/<str:user_id>/', views.chat_user, name='chat'),
    path('sent-message/<int:user_id>', views.sent_message, name="sent-message"),
]

posts/urls.py
from django.urls import path
from . import views

app_name = "posts"
urlpatterns = [
    path('create-post', views.create_post, name='create-post'),
    path('delete-post/<int:post_id>', views.delete_post, name='delete-post'),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    # path('', views.home, name='home'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('register-user/', views.register, name='register-user'),
    path('profile/', views.profile, name='profile'),
    path('profile/<int:user_id>/', views.user_profile, name='user-profile'),
    path('follow/<int:user_id>/', views.follow_user, name='follow'),
    path('unfollow/<int:user_id>/', views.unfollow_user, name='unfollow'),
    path('update-fullname/', views.update_fullname, name='update-fullname'),
    path('update-profilepic/', views.update_profilepic, name='update-profilepic'),
]

templates/base.html
{% load static tailwind_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
        <title>Keralagram</title>
    {% endblock title %}
    {% tailwind_css %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link rel="icon" type="image/x-icon" href="{% static '/images/letter-k.png' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/css/base.css' %}">
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    {% comment %} <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/emojionearea/3.4.2/emojionearea.min.js" integrity="sha512-hkvXFLlESjeYENO4CNi69z3A1puvONQV5Uh+G4TUDayZxSLyic5Kba9hhuiNLbHqdnKNMk2PxXKm0v7KDnWkYA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script> {% endcomment %}
</head>
<body class="bg-gray-900 text-blue-green">
    <noscript>You need to enable JavaScript to run this app.</noscript>
    {% comment %} {% block header %}
        {% include 'header.html' %}
    {% endblock header %}   {% endcomment %}
    {% include 'loader.html' %}
    {% block main_content %}{% endblock main_content %}
    <script>
        const chatSocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/online/'
        );
        const notifySocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/notifications/'
        );

        notifySocket.onmessage = function(e) {
            const data = JSON.parse(e.data);
            console.log(data);
        };
        notifySocket.onclose = function(e) {
            console.error('Chat socket closed unexpectedly');
        };
    </script>
</body>
</html>

templates/emoji.html
{% load static %}
{% block emoji_picker %}
<link rel="stylesheet" type="text/css" href="{% static '/css/emoji_picker.css' %}">
<div id="emoji-picker" class="z-50 bg-gray-800 text-blue-green rounded-2xl p-4 absolute top-16 right-0 w-96 h-96 hidden flex-col items-start overflow-y-scroll">
    <span class="font-bold">Recent</span>
    <div class="emoji-category">
        <span class="emoji cursor-pointer text-xl">&#128512</span>
        <span class="emoji cursor-pointer text-xl">&#128513</span>
        <span class="emoji cursor-pointer text-xl">&#128514</span>
        <span class="emoji cursor-pointer text-xl">&#128515</span>
        <span class="emoji cursor-pointer text-xl">&#128516</span>
        <span class="emoji cursor-pointer text-xl">&#128517</span>
        <span class="emoji cursor-pointer text-xl">&#128518</span>
        <span class="emoji cursor-pointer text-xl">&#128519</span>
        <span class="emoji cursor-pointer text-xl">&#128520</span>
    </div>
    <span class="font-bold">Smileys and emotions</span>
    <div class="emoji-category">
        <span class="emoji cursor-pointer text-xl">&#128512</span>
        <span class="emoji cursor-pointer text-xl">&#128513</span>
        <span class="emoji cursor-pointer text-xl">&#128514</span>
        <span class="emoji cursor-pointer text-xl">&#128515</span>
        <span class="emoji cursor-pointer text-xl">&#128516</span>
        <span class="emoji cursor-pointer text-xl">&#128517</span>
        <span class="emoji cursor-pointer text-xl">&#128518</span>
        <span class="emoji cursor-pointer text-xl">&#128519</span>
        <span class="emoji cursor-pointer text-xl">&#128520</span>
        <span class="emoji cursor-pointer text-xl">&#128127</span>
        <span class="emoji cursor-pointer text-xl">&#128128</span>
        <span class="emoji cursor-pointer text-xl">&#129324</span>  
        <span class="emoji cursor-pointer text-xl">&#128521</span>
        <span class="emoji cursor-pointer text-xl">&#128522</span>
        <span class="emoji cursor-pointer text-xl">&#128523</span>
        <span class="emoji cursor-pointer text-xl">&#128524</span>
        <span class="emoji cursor-pointer text-xl">&#128525</span>
        <span class="emoji cursor-pointer text-xl">&#128526</span>
        <span class="emoji cursor-pointer text-xl">&#128527</span>
        <span class="emoji cursor-pointer text-xl">&#128528</span>
        <span class="emoji cursor-pointer text-xl">&#128529</span>
        <span class="emoji cursor-pointer text-xl">&#128530</span>
        <span class="emoji cursor-pointer text-xl">&#128531</span>
        <span class="emoji cursor-pointer text-xl">&#128532</span>
        <span class="emoji cursor-pointer text-xl">&#128533</span>
        <span class="emoji cursor-pointer text-xl">&#128534</span>
        <span class="emoji cursor-pointer text-xl">&#128535</span>
        <span class="emoji cursor-pointer text-xl">&#128536</span>
        <span class="emoji cursor-pointer text-xl">&#128537</span>
        <span class="emoji cursor-pointer text-xl">&#128538</span>
        <span class="emoji cursor-pointer text-xl">&#128539</span>
        <span class="emoji cursor-pointer text-xl">&#128540</span>
        <span class="emoji cursor-pointer text-xl">&#128541</span>
        <span class="emoji cursor-pointer text-xl">&#128542</span>
        <span class="emoji cursor-pointer text-xl">&#128543</span>
        <span class="emoji cursor-pointer text-xl">&#128544</span>
        <span class="emoji cursor-pointer text-xl">&#128545</span>
        <span class="emoji cursor-pointer text-xl">&#128546</span>
        <span class="emoji cursor-pointer text-xl">&#128547</span>
        <span class="emoji cursor-pointer text-xl">&#128548</span>
        <span class="emoji cursor-pointer text-xl">&#128549</span>
        <span class="emoji cursor-pointer text-xl">&#128550</span>
        <span class="emoji cursor-pointer text-xl">&#128551</span>
        <span class="emoji cursor-pointer text-xl">&#128552</span>
        <span class="emoji cursor-pointer text-xl">&#128553</span>
        <span class="emoji cursor-pointer text-xl">&#128554</span>
        <span class="emoji cursor-pointer text-xl">&#128555</span>
        <span class="emoji cursor-pointer text-xl">&#128556</span>
        <span class="emoji cursor-pointer text-xl">&#128557</span>
        <span class="emoji cursor-pointer text-xl">&#128558</span>
        <span class="emoji cursor-pointer text-xl">&#128559</span>
        <span class="emoji cursor-pointer text-xl">&#128560</span>
        <span class="emoji cursor-pointer text-xl">&#128561</span>
        <span class="emoji cursor-pointer text-xl">&#128562</span>
        <span class="emoji cursor-pointer text-xl">&#128563</span>
        <span class="emoji cursor-pointer text-xl">&#128564</span>
        <span class="emoji cursor-pointer text-xl">&#128565</span>
        <span class="emoji cursor-pointer text-xl">&#128566</span>
        <span class="emoji cursor-pointer text-xl">&#128567</span>
        <span class="emoji cursor-pointer text-xl">&#128577</span>
        <span class="emoji cursor-pointer text-xl">&#128578</span>
        <span class="emoji cursor-pointer text-xl">&#128579</span>
        <span class="emoji cursor-pointer text-xl">&#128580</span>
        <span class="emoji cursor-pointer text-xl">&#129296</span>
        <span class="emoji cursor-pointer text-xl">&#129296</span>
        <span class="emoji cursor-pointer text-xl">&#129297</span>
        <span class="emoji cursor-pointer text-xl">&#129298</span>
        <span class="emoji cursor-pointer text-xl">&#129299</span>
        <span class="emoji cursor-pointer text-xl">&#129300</span>
        <span class="emoji cursor-pointer text-xl">&#129301</span>
        <span class="emoji cursor-pointer text-xl">&#129303</span>
        <span class="emoji cursor-pointer text-xl">&#129312</span>
        <span class="emoji cursor-pointer text-xl">&#129314</span>
        <span class="emoji cursor-pointer text-xl">&#129315</span>
        <span class="emoji cursor-pointer text-xl">&#129316</span>
        <span class="emoji cursor-pointer text-xl">&#129317</span>
        <span class="emoji cursor-pointer text-xl">&#129319</span>
        <span class="emoji cursor-pointer text-xl">&#129320</span>
        <span class="emoji cursor-pointer text-xl">&#129321</span>
        <span class="emoji cursor-pointer text-xl">&#129322</span>
        <span class="emoji cursor-pointer text-xl">&#129323</span>
        <span class="emoji cursor-pointer text-xl">&#129325</span>
        <span class="emoji cursor-pointer text-xl">&#129326</span>
        <span class="emoji cursor-pointer text-xl">&#129327</span>
        <span class="emoji cursor-pointer text-xl">&#129392</span>
        <span class="emoji cursor-pointer text-xl">&#129393</span>
        <span class="emoji cursor-pointer text-xl">&#129395</span>
        <span class="emoji cursor-pointer text-xl">&#129396</span>
        <span class="emoji cursor-pointer text-xl">&#129397</span>
        <span class="emoji cursor-pointer text-xl">&#129398</span>
        <span class="emoji cursor-pointer text-xl">&#129402</span>
        <span class="emoji cursor-pointer text-xl">&#129488</span>
    </div>
    <span class="font-bold">Cat faces</span>
    <div class="emoji-category">
        <span class="emoji cursor-pointer text-xl">&#128568</span>
        <span class="emoji cursor-pointer text-xl">&#128567</span>
        <span class="emoji cursor-pointer text-xl">&#128568</span>
        <span class="emoji cursor-pointer text-xl">&#128569</span>
        <span class="emoji cursor-pointer text-xl">&#128570</span>
        <span class="emoji cursor-pointer text-xl">&#128571</span>
        <span class="emoji cursor-pointer text-xl">&#128572</span>
        <span class="emoji cursor-pointer text-xl">&#128573</span>
        <span class="emoji cursor-pointer text-xl">&#128574</span>
        <span class="emoji cursor-pointer text-xl">&#128575</span>
        <span class="emoji cursor-pointer text-xl">&#128576</span>
        <span class="emoji cursor-pointer text-xl">&#128584</span>
        <span class="emoji cursor-pointer text-xl">&#128585</span>
        <span class="emoji cursor-pointer text-xl">&#128586</span>
    </div>
    <span class="font-bold">Hand gestures</span>
    <div class="emoji-category">
        <span class="emoji cursor-pointer text-xl">&#9995</span>
        <span class="emoji cursor-pointer text-xl">&#128075</span>
        <span class="emoji cursor-pointer text-xl">&#128400</span>
        <span class="emoji cursor-pointer text-xl">&#128406</span>
        <span class="emoji cursor-pointer text-xl">&#129306</span>
        <span class="emoji cursor-pointer text-xl">&#9757</span>
        <span class="emoji cursor-pointer text-xl">&#128070</span>
        <span class="emoji cursor-pointer text-xl">&#128071</span>
        <span class="emoji cursor-pointer text-xl">&#128072</span>
        <span class="emoji cursor-pointer text-xl">&#128073</span>
        <span class="emoji cursor-pointer text-xl">&#128405</span>
        <span class="emoji cursor-pointer text-xl">&#9994</span>
        <span class="emoji cursor-pointer text-xl">&#128070</span>
        <span class="emoji cursor-pointer text-xl">&#128071</span>
        <span class="emoji cursor-pointer text-xl">&#128072</span>
        <span class="emoji cursor-pointer text-xl">&#128073</span>
        <span class="emoji cursor-pointer text-xl">&#128405</span>
    </div>
    <span class="font-bold">People</span>
    <div class="emoji-category">
        <span class="emoji cursor-pointer text-xl">&#128512</span>
        <span class="emoji cursor-pointer text-xl">&#128513</span>
        <span class="emoji cursor-pointer text-xl">&#128514</span>
        <span class="emoji cursor-pointer text-xl">&#128515</span>
        <span class="emoji cursor-pointer text-xl">&#128516</span>
        <span class="emoji cursor-pointer text-xl">&#128517</span>
        <span class="emoji cursor-pointer text-xl">&#128518</span>
        <span class="emoji cursor-pointer text-xl">&#128519</span>
        <span class="emoji cursor-pointer text-xl">&#128520</span>
    </div>
    <span class="font-bold">Office related</span>
    <div class="emoji-category">
        <span class="emoji cursor-pointer text-xl">&#128512</span>
        <span class="emoji cursor-pointer text-xl">&#128513</span>
        <span class="emoji cursor-pointer text-xl">&#128514</span>
        <span class="emoji cursor-pointer text-xl">&#128515</span>
        <span class="emoji cursor-pointer text-xl">&#128516</span>
        <span class="emoji cursor-pointer text-xl">&#128517</span>
        <span class="emoji cursor-pointer text-xl">&#128518</span>
        <span class="emoji cursor-pointer text-xl">&#128519</span>
        <span class="emoji cursor-pointer text-xl">&#128520</span>
    </div>
    <span class="font-bold">Places</span>
    <div class="emoji-category">
        <span class="emoji cursor-pointer text-xl">&#128512</span>
        <span class="emoji cursor-pointer text-xl">&#128513</span>
        <span class="emoji cursor-pointer text-xl">&#128514</span>
        <span class="emoji cursor-pointer text-xl">&#128515</span>
        <span class="emoji cursor-pointer text-xl">&#128516</span>
        <span class="emoji cursor-pointer text-xl">&#128517</span>
        <span class="emoji cursor-pointer text-xl">&#128518</span>
        <span class="emoji cursor-pointer text-xl">&#128519</span>
        <span class="emoji cursor-pointer text-xl">&#128520</span>
    </div>
    <!-- Add more emojis as needed -->
</div>
{% endblock emoji_picker %}

templates/header.html
{% block header %}
    <div class='header-section'>
        {% if user.is_authenticated %}
        <a title="View profile" href="{% url 'users:profile' %}"><span id="user-name">Hi, {{user.username}}</span></a>
        <a href="{% url 'users:logout' %}">
            <span title="Logout" class="material-symbols-outlined">
                logout
            </span>
        </a>
        {% endif %}
        <a title="Home" href="{% url 'home' %}">
            <span class="material-symbols-outlined">
                home_app_logo
            </span>
        </a>
        <div class="header-icons">
            <span title="Notifications" class="material-symbols-outlined">
                notifications
            </span>
            <span title="Options" class="material-symbols-outlined">
                menu
            </span>
        </div>
    </div>  
    <!-- Breadcrumbs -->
    {% comment %} <div class="breadcrumbs">
        {% for name, url in breadcrumbs %}
            {% if name != 'Home' %}
                >>
            {% endif %}
            
            {% if forloop.last %}
                <span class="breadcrumb-item active">{{ name }}</span>
            {% else %}
                <a href="{{ url }}"><span class="breadcrumb-item">{{ name }}</span></a>
            {% endif %}
        {% endfor %}
    </div>  {% endcomment %}
{% endblock header %}
    

templates/loader.html
<!-- loader.html -->
{% load static %}
<link rel="stylesheet" href="{% static '/css/loader.css' %}">
<div id="loader" class="loader-container">
    <img class="loader" src="{% static '/images/waiting.png' %}" alt="loader">
</div>
<script>
    const loader = document.getElementById("loader");
        window.addEventListener('load', (event) => {
            loader.style.display = "none";
        });
</script>

templates/navbar.html
{% load static %}
{% block navbar %}
    {% comment %} <link rel="stylesheet" type="text/css" href="{% static '/css/navbar.css' %}"> {% endcomment %}
    <div class="md:flex sm:hidden flex-col h-screen w-1/4 items-center p-2 mt-4 text-blue-green text-lg z-10">
                <div class="flex flex-col items-center cursor-pointer mb-5 sm:hidden md:flex">
                    <a href="{% url 'users:profile' %}">
                        <div class="flex flex-row p-2 bg-gradient-to-r from-blue-300 to-violet-300 rounded-full">
                            {% if current_user.user.useraccount.profile_pic %}
                                <img class="h-24 w-24 rounded-full" src="/media/{{current_user.user.useraccount.profile_pic}}" alt="Profile pic">
                            {% else %} 
                                <img class="h-24 w-24 rounded-full" src="{% static '/images/navbar/user.png' %}" alt="profile pic"> 
                            {% endif %} 
                        </div>
                    </a>
                    <a href="{% url 'users:profile' %}">
                        <span class="text-2xl font-bold text-blue-green">{{user.useraccount.full_name}}</span>
                    </a>
                    <span class="font-bold text-gray-400">@{{user}}</span>
                    <span class="font-bold text-green-500 flex items-center gap-1">
                        <b class="text-2xl">•</b> online
                    </span>
                </div>
                <a href="{% url 'home' %}" class="cursor-pointer h-14 w-full pl-2 
                    {% if location == 'home' %}
                        bg-gradient-to-r from-blue-300 to-violet-300 text-gray-900 rounded-2xl
                    {% else %}
                        move-right
                    {% endif %}
                    flex gap-2 items-center justify-items-center">
                    {% if location == 'home' %}
                        <img class="h-8 w-8 opacity-80" src="{% static '/images/navbar/home-black.png' %}" alt="Home">
                    {% else %}
                        <img class="h-8 w-8 opacity-80" src="{% static '/images/navbar/home.png' %}" alt="Home">
                    {% endif %}
                    <h3 class="font-bold sm:hidden md:block">Home</h3>
                </a>
                <div class="move-right cursor-pointer h-14 w-full pl-2 flex gap-2 items-center justify-items-center">
                    <img class="h-8 w-8" src="{% static '/images/navbar/search.png' %}" alt="Search">
                    <h3 class="font-bold sm:hidden md:block">Search</h3>
                </div>
                <div class="move-right cursor-pointer h-14 w-full pl-2 flex gap-2 items-center justify-items-center">
                    <img class="h-8 w-8" src="{% static '/images/navbar/explore.png' %}" alt="Explore">
                    <h3 class="font-bold sm:hidden md:block">Explore</h3>
                </div>
                <a href="{% url 'messenger:home' %}" class="move-right cursor-pointer h-14 w-full pl-2
                    {% if location == 'messenger' %}
                        bg-gradient-to-r from-blue-300 to-violet-300 text-gray-900 rounded-2xl
                    {% else %}
                        move-right
                    {% endif %}
                    flex gap-2 items-center justify-items-center">
                    <img class="h-8 w-8" src="{% static '/images/navbar/chat.png' %}" alt="Chat">
                    <h3 class="font-bold sm:hidden md:block">Messages</h3>
                </a>
                <a href="{% url 'users:profile' %}" class="cursor-pointer h-14 w-full pl-2 
                    {% if location == 'profile' %}
                        bg-gradient-to-r from-blue-300 to-violet-300 text-gray-900 rounded-2xl
                    {% else %}
                        move-right
                    {% endif %}
                    flex gap-2 items-center justify-items-center">
                    {% if location == 'profile' %}
                        <img class="h-8 w-8" src="{% static '/images/navbar/profile-black.png' %}" alt="Profile">
                    {% else %}
                        <img class="h-8 w-8" src="{% static '/images/navbar/profile-icon.png' %}" alt="Profile">
                    {% endif %}
                    <h3 class="font-bold sm:hidden md:block">My Profile</h3>
                </a>
                <div class="move-right cursor-pointer h-14 w-full pl-2 flex gap-2 items-center justify-items-center">
                    <img class="h-8 w-8" src="{% static '/images/navbar/settings.png' %}" alt="Settings">
                    <h3 class="font-bold sm:hidden md:block">Settings</h3>
                </div>
                <div id="logout" class="move-right cursor-pointer h-14 w-full pl-2 flex gap-2 items-center justify-items-center">
                    <img class="h-8 w-8" src="{% static '/images/navbar/log-out.png' %}" alt="Logout">
                    <h3 class="font-bold sm:hidden md:block">Log Out</h3>
                </div>
                <div id="logout-popup" class="hidden flex-col gap-4 w-1/4 h-1/4 items-center justify-between absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 z-10 bg-gray-900 text-gray-400 p-6 rounded-2xl">
                    <span class="font-bold">Are you sure?</span>
                    <div class="flex gap-4 w-full text-gray-800">
                        <span id="cancel-logout" class="font-bold bg-blue-200 rounded-full w-1/2 flex justify-center p-2 cursor-pointer">No</span>
                        <a href="{% url 'users:logout' %}" class="font-bold bg-red-200 rounded-full w-1/2 flex justify-center p-2 cursor-pointer">
                            <span id="confirm-logout" >Yes</span>
                        </a>
                    </div>
                </div>
            </div>
            <script>
                const logout = document.getElementById("logout");
                const logoutPopup = document.getElementById("logout-popup");
                const cancelLogout = document.getElementById("cancel-logout");
                logout.addEventListener("click", ()=>{
                    logoutPopup.classList.remove("hidden");
                    logoutPopup.classList.add("flex");
                })
                cancelLogout.addEventListener("click", ()=>{
                    logoutPopup.classList.remove("flex");
                    logoutPopup.classList.add("hidden");
                })
            </script>
{% endblock navbar %}